# Generated by Django 4.0 on 2022-10-29 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=64, verbose_name='slug')),
                ('bg_url', models.CharField(blank=True, max_length=500, null=True)),
                ('font', models.CharField(blank=True, max_length=100, null=True)),
                ('font_link', models.CharField(blank=True, max_length=300, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('default_card_color', models.CharField(blank=True, max_length=20, null=True)),
                ('heading_size', models.CharField(blank=True, max_length=5, null=True)),
                ('points_size', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('points', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=64, null=True, verbose_name='slug')),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_group', to='counter.event')),
            ],
        ),
        migrations.CreateModel(
            name='PointsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_group', to='counter.group')),
            ],
            options={
                'verbose_name_plural': 'Points histories',
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['name'], name='group_name_idx'),
        ),
    ]
