# Generated by Django 4.0.4 on 2022-09-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('group', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
            ],
        ),
    ]
