# Generated by Django 4.0.4 on 2022-09-28 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PointsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.IntegerField(default=0)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history_group', to='counter.group')),
            ],
            options={
                'verbose_name_plural': 'Points histories',
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['name'], name='group_name_idx'),
        ),
    ]
