# Generated by Django 4.0.4 on 2022-09-28 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Points',
            new_name='PointsRecord',
        ),
    ]
