# Generated by Django 4.0.4 on 2022-10-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='css',
        ),
        migrations.AddField(
            model_name='event',
            name='bg_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
