# Generated by Django 4.0.4 on 2022-09-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_rename_points_pointsrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsrecord',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='pointsrecord',
            index=models.Index(fields=['group'], name='group_idx'),
        ),
    ]
