# Generated by Django 4.0.4 on 2022-10-03 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_remove_event_css_event_bg_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(max_length=64, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='group',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_group', to='counter.event'),
        ),
    ]
