# Generated by Django 4.0.4 on 2022-10-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_event_group_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=64, null=True, verbose_name='slug'),
        ),
    ]
