# Generated by Django 4.0.4 on 2022-10-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_event_color_event_default_card_color_event_font_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='font_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
