# Generated by Django 4.0.4 on 2022-10-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0005_event_font_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='heading_size',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='points_size',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
